spring.application.name=notificationservice

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.properties.hibernate.format_sql=true

spring.flyway.enabled=true

app.jwt.secret=qPsJuSuX7rPS7oAGcR8NOHDSi/r5w8UsyPcJ3Jm7znE=

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=2000

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

server.port=8083
