services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: projecthub-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  workhub-gateway:
    image: 258227418027.dkr.ecr.ap-south-2.amazonaws.com/workhub-gateway
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - SPRING_PROFILES_ACTIVE=prod
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_SERVICE_AUTH_URL=http://workhub-auth:8082
      - APP_SERVICE_NOTIFICATIONS_URL=http://workhub-notifications:8083
      - APP_SERVICE_CORE_URL=http://workhub-core:8081
      - APP_SERVICE_NOTIFICATIONS_WS_URL=ws://workhub-notifications:8083/ws
    depends_on:
      - workhub-core
      - workhub-auth
      - workhub-notifications
    env_file: .env

  workhub-core:
    image: 258227418027.dkr.ecr.ap-south-2.amazonaws.com/workhub-core
    ports:
      - "8081:8081"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./core-uploads:/app/uploads
    depends_on:
      - rabbitmq
    env_file: .env

  workhub-auth:
    image: 258227418027.dkr.ecr.ap-south-2.amazonaws.com/workhub-auth
    ports:
      - "8082:8082"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_AUTH}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${APP_JWT_SECRET}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - rabbitmq
    env_file: .env

  workhub-notifications:
    image: 258227418027.dkr.ecr.ap-south-2.amazonaws.com/workhub-notifications
    ports:
      - "8083:8083"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_NOTIFICATIONS}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - rabbitmq
    env_file: .env
