server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: false
  application:
    name: gateway-service

app:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
